# Generated by Django 5.1.4 on 2024-12-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_goodsin_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
