# Generated by Django 5.1.4 on 2024-12-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_itemmaster_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmaster',
            name='stock',
        ),
    ]
