# Generated by Django 5.1.4 on 2024-12-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_itemmaster_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmaster',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
